// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: racecarweb/lctmanager/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetLctRequest defines the QueryGetLctRequest message.
type QueryGetLctRequest struct {
	LctId string `protobuf:"bytes,1,opt,name=lct_id,json=lctId,proto3" json:"lct_id,omitempty"`
}

func (m *QueryGetLctRequest) Reset()         { *m = QueryGetLctRequest{} }
func (m *QueryGetLctRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLctRequest) ProtoMessage()    {}
func (*QueryGetLctRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{2}
}
func (m *QueryGetLctRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLctRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLctRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLctRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLctRequest.Merge(m, src)
}
func (m *QueryGetLctRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLctRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLctRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLctRequest proto.InternalMessageInfo

func (m *QueryGetLctRequest) GetLctId() string {
	if m != nil {
		return m.LctId
	}
	return ""
}

// QueryGetLctResponse defines the QueryGetLctResponse message.
type QueryGetLctResponse struct {
	LinkedContextToken string `protobuf:"bytes,1,opt,name=linked_context_token,json=linkedContextToken,proto3" json:"linked_context_token,omitempty"`
}

func (m *QueryGetLctResponse) Reset()         { *m = QueryGetLctResponse{} }
func (m *QueryGetLctResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLctResponse) ProtoMessage()    {}
func (*QueryGetLctResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{3}
}
func (m *QueryGetLctResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLctResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLctResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLctResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLctResponse.Merge(m, src)
}
func (m *QueryGetLctResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLctResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLctResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLctResponse proto.InternalMessageInfo

func (m *QueryGetLctResponse) GetLinkedContextToken() string {
	if m != nil {
		return m.LinkedContextToken
	}
	return ""
}

// QueryGetComponentRelationshipsRequest defines the QueryGetComponentRelationshipsRequest message.
type QueryGetComponentRelationshipsRequest struct {
	ComponentId string `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
}

func (m *QueryGetComponentRelationshipsRequest) Reset()         { *m = QueryGetComponentRelationshipsRequest{} }
func (m *QueryGetComponentRelationshipsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetComponentRelationshipsRequest) ProtoMessage()    {}
func (*QueryGetComponentRelationshipsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{4}
}
func (m *QueryGetComponentRelationshipsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetComponentRelationshipsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetComponentRelationshipsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetComponentRelationshipsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetComponentRelationshipsRequest.Merge(m, src)
}
func (m *QueryGetComponentRelationshipsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetComponentRelationshipsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetComponentRelationshipsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetComponentRelationshipsRequest proto.InternalMessageInfo

func (m *QueryGetComponentRelationshipsRequest) GetComponentId() string {
	if m != nil {
		return m.ComponentId
	}
	return ""
}

// QueryGetComponentRelationshipsResponse defines the QueryGetComponentRelationshipsResponse message.
type QueryGetComponentRelationshipsResponse struct {
	ComponentRelationships string `protobuf:"bytes,1,opt,name=component_relationships,json=componentRelationships,proto3" json:"component_relationships,omitempty"`
	LctCount               int64  `protobuf:"varint,2,opt,name=lct_count,json=lctCount,proto3" json:"lct_count,omitempty"`
}

func (m *QueryGetComponentRelationshipsResponse) Reset() {
	*m = QueryGetComponentRelationshipsResponse{}
}
func (m *QueryGetComponentRelationshipsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetComponentRelationshipsResponse) ProtoMessage()    {}
func (*QueryGetComponentRelationshipsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{5}
}
func (m *QueryGetComponentRelationshipsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetComponentRelationshipsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetComponentRelationshipsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetComponentRelationshipsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetComponentRelationshipsResponse.Merge(m, src)
}
func (m *QueryGetComponentRelationshipsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetComponentRelationshipsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetComponentRelationshipsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetComponentRelationshipsResponse proto.InternalMessageInfo

func (m *QueryGetComponentRelationshipsResponse) GetComponentRelationships() string {
	if m != nil {
		return m.ComponentRelationships
	}
	return ""
}

func (m *QueryGetComponentRelationshipsResponse) GetLctCount() int64 {
	if m != nil {
		return m.LctCount
	}
	return 0
}

// QueryValidateLctAccessRequest defines the QueryValidateLctAccessRequest message.
type QueryValidateLctAccessRequest struct {
	LctId       string `protobuf:"bytes,1,opt,name=lct_id,json=lctId,proto3" json:"lct_id,omitempty"`
	RequestorId string `protobuf:"bytes,2,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
}

func (m *QueryValidateLctAccessRequest) Reset()         { *m = QueryValidateLctAccessRequest{} }
func (m *QueryValidateLctAccessRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidateLctAccessRequest) ProtoMessage()    {}
func (*QueryValidateLctAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{6}
}
func (m *QueryValidateLctAccessRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidateLctAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidateLctAccessRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidateLctAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidateLctAccessRequest.Merge(m, src)
}
func (m *QueryValidateLctAccessRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidateLctAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidateLctAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidateLctAccessRequest proto.InternalMessageInfo

func (m *QueryValidateLctAccessRequest) GetLctId() string {
	if m != nil {
		return m.LctId
	}
	return ""
}

func (m *QueryValidateLctAccessRequest) GetRequestorId() string {
	if m != nil {
		return m.RequestorId
	}
	return ""
}

// QueryValidateLctAccessResponse defines the QueryValidateLctAccessResponse message.
type QueryValidateLctAccessResponse struct {
	HasAccess   bool   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	AccessLevel string `protobuf:"bytes,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
}

func (m *QueryValidateLctAccessResponse) Reset()         { *m = QueryValidateLctAccessResponse{} }
func (m *QueryValidateLctAccessResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidateLctAccessResponse) ProtoMessage()    {}
func (*QueryValidateLctAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_667fcbfb88eed80d, []int{7}
}
func (m *QueryValidateLctAccessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidateLctAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidateLctAccessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidateLctAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidateLctAccessResponse.Merge(m, src)
}
func (m *QueryValidateLctAccessResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidateLctAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidateLctAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidateLctAccessResponse proto.InternalMessageInfo

func (m *QueryValidateLctAccessResponse) GetHasAccess() bool {
	if m != nil {
		return m.HasAccess
	}
	return false
}

func (m *QueryValidateLctAccessResponse) GetAccessLevel() string {
	if m != nil {
		return m.AccessLevel
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "racecarweb.lctmanager.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "racecarweb.lctmanager.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetLctRequest)(nil), "racecarweb.lctmanager.v1.QueryGetLctRequest")
	proto.RegisterType((*QueryGetLctResponse)(nil), "racecarweb.lctmanager.v1.QueryGetLctResponse")
	proto.RegisterType((*QueryGetComponentRelationshipsRequest)(nil), "racecarweb.lctmanager.v1.QueryGetComponentRelationshipsRequest")
	proto.RegisterType((*QueryGetComponentRelationshipsResponse)(nil), "racecarweb.lctmanager.v1.QueryGetComponentRelationshipsResponse")
	proto.RegisterType((*QueryValidateLctAccessRequest)(nil), "racecarweb.lctmanager.v1.QueryValidateLctAccessRequest")
	proto.RegisterType((*QueryValidateLctAccessResponse)(nil), "racecarweb.lctmanager.v1.QueryValidateLctAccessResponse")
}

func init() {
	proto.RegisterFile("racecarweb/lctmanager/v1/query.proto", fileDescriptor_667fcbfb88eed80d)
}

var fileDescriptor_667fcbfb88eed80d = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x4f, 0x13, 0x4f,
	0x14, 0xef, 0xf2, 0x0f, 0x1b, 0x3a, 0xfc, 0x2f, 0x8c, 0xa8, 0x58, 0x65, 0x85, 0x55, 0x0c, 0x82,
	0x74, 0x2c, 0x1c, 0xe0, 0xa6, 0xd2, 0x28, 0x62, 0xd0, 0xe8, 0xc6, 0x98, 0xc8, 0x65, 0x33, 0x9d,
	0x9d, 0x2c, 0x1b, 0xb6, 0x33, 0xcb, 0xce, 0x50, 0x21, 0x04, 0x63, 0xfc, 0x04, 0x24, 0xde, 0xfc,
	0x04, 0x1e, 0xfd, 0x18, 0x1c, 0x49, 0x4c, 0x8c, 0x27, 0x63, 0xc0, 0xc4, 0x93, 0xdf, 0xc1, 0xec,
	0xcc, 0x94, 0xb6, 0xc1, 0xed, 0xaa, 0x97, 0x66, 0xfa, 0xde, 0xef, 0xfd, 0xde, 0xef, 0x37, 0xf3,
	0xde, 0x82, 0xeb, 0x29, 0x26, 0x94, 0xe0, 0xf4, 0x15, 0x6d, 0xa0, 0x98, 0xc8, 0x26, 0x66, 0x38,
	0xa4, 0x29, 0x6a, 0xd5, 0xd0, 0xd6, 0x36, 0x4d, 0x77, 0xab, 0x49, 0xca, 0x25, 0x87, 0x63, 0x1d,
	0x54, 0xb5, 0x83, 0xaa, 0xb6, 0x6a, 0x95, 0x11, 0xdc, 0x8c, 0x18, 0x47, 0xea, 0x57, 0x83, 0x2b,
	0x33, 0x84, 0x8b, 0x26, 0x17, 0xa8, 0x81, 0x05, 0xd5, 0x2c, 0xa8, 0x55, 0x6b, 0x50, 0x89, 0x6b,
	0x28, 0xc1, 0x61, 0xc4, 0xb0, 0x8c, 0x38, 0x33, 0xd8, 0xd1, 0x90, 0x87, 0x5c, 0x1d, 0x51, 0x76,
	0x32, 0xd1, 0x2b, 0x21, 0xe7, 0x61, 0x4c, 0x11, 0x4e, 0x22, 0x84, 0x19, 0xe3, 0x52, 0x95, 0x08,
	0x93, 0x9d, 0xca, 0x95, 0x9c, 0xe0, 0x14, 0x37, 0x0d, 0xcc, 0x1d, 0x05, 0xf0, 0x59, 0xd6, 0xfc,
	0xa9, 0x0a, 0x7a, 0x74, 0x6b, 0x9b, 0x0a, 0xe9, 0xae, 0x83, 0x73, 0x3d, 0x51, 0x91, 0x70, 0x26,
	0x28, 0xac, 0x03, 0x5b, 0x17, 0x8f, 0x59, 0x13, 0xd6, 0xf4, 0xf0, 0xfc, 0x44, 0x35, 0xcf, 0x71,
	0x55, 0x57, 0x2e, 0x97, 0x0f, 0xbf, 0x5e, 0x2d, 0x7d, 0xf8, 0xf1, 0x71, 0xc6, 0xf2, 0x4c, 0xa9,
	0x3b, 0x6b, 0x3a, 0xae, 0x50, 0xb9, 0x46, 0xa4, 0xe9, 0x08, 0xcf, 0x03, 0x3b, 0x26, 0xd2, 0x8f,
	0x02, 0x45, 0x5d, 0xf6, 0x06, 0x63, 0x22, 0x57, 0x03, 0x77, 0xc5, 0x08, 0x69, 0x83, 0x8d, 0x90,
	0xdb, 0x60, 0x34, 0x8e, 0xd8, 0x26, 0x0d, 0x7c, 0xc2, 0x99, 0xa4, 0x3b, 0xd2, 0x97, 0x7c, 0x93,
	0x32, 0x53, 0x0b, 0x75, 0xae, 0xae, 0x53, 0xcf, 0xb3, 0x8c, 0xfb, 0x08, 0x4c, 0xb5, 0x89, 0xea,
	0xbc, 0x99, 0x70, 0x46, 0x99, 0xf4, 0x68, 0xac, 0xaf, 0x6c, 0x23, 0x4a, 0xda, 0xd6, 0xe1, 0x24,
	0xf8, 0x9f, 0xb4, 0x01, 0x1d, 0x39, 0xc3, 0xa7, 0xb1, 0xd5, 0xc0, 0x7d, 0x0d, 0x6e, 0x14, 0x71,
	0x19, 0x9d, 0x8b, 0xe0, 0x62, 0x87, 0x2c, 0xed, 0x86, 0x18, 0xde, 0x0b, 0xe4, 0xb7, 0x04, 0xf0,
	0x32, 0x28, 0x67, 0xd7, 0x41, 0xf8, 0x36, 0x93, 0x63, 0x03, 0x13, 0xd6, 0xf4, 0x7f, 0xde, 0x50,
	0x4c, 0x64, 0x3d, 0xfb, 0xef, 0xbe, 0x04, 0xe3, 0xaa, 0xff, 0x0b, 0x1c, 0x47, 0x01, 0x96, 0x74,
	0x8d, 0xc8, 0x7b, 0x84, 0x50, 0x21, 0xfa, 0x5f, 0x66, 0x66, 0x2d, 0xd5, 0x08, 0x9e, 0x66, 0xc9,
	0x01, 0x6d, 0xed, 0x34, 0xb6, 0x1a, 0xb8, 0x0d, 0xe0, 0xe4, 0x51, 0x1b, 0x4b, 0xe3, 0x00, 0x6c,
	0x60, 0xe1, 0x63, 0x15, 0x55, 0xfc, 0x43, 0x5e, 0x79, 0x03, 0x0b, 0x0d, 0xcb, 0x7a, 0xe8, 0x94,
	0x1f, 0xd3, 0x16, 0x8d, 0xdb, 0x3d, 0x74, 0x6c, 0x2d, 0x0b, 0xcd, 0xbf, 0xb1, 0xc1, 0xa0, 0x6a,
	0x02, 0x0f, 0x2c, 0x60, 0xeb, 0x41, 0x81, 0xb7, 0xf2, 0x47, 0xe9, 0xec, 0x7c, 0x56, 0xe6, 0xfe,
	0x10, 0xad, 0x35, 0xbb, 0x37, 0xdf, 0x7e, 0xfa, 0xfe, 0x6e, 0xe0, 0x1a, 0x9c, 0x44, 0xa6, 0x6c,
	0x2e, 0x6f, 0x2b, 0xe0, 0x7b, 0x0b, 0xd8, 0x7a, 0xd8, 0x0a, 0x25, 0xf5, 0x0c, 0x70, 0xa1, 0xa4,
	0xde, 0x09, 0x76, 0x17, 0x94, 0xa4, 0x39, 0x38, 0xdb, 0x47, 0x52, 0x48, 0xa5, 0x1f, 0x13, 0x89,
	0xf6, 0xf4, 0x63, 0xee, 0xc3, 0x9f, 0x16, 0xb8, 0x94, 0x3b, 0x74, 0xf0, 0x4e, 0xb1, 0x82, 0xbe,
	0xa3, 0x5f, 0xb9, 0xfb, 0xef, 0x04, 0xc6, 0xd5, 0x63, 0xe5, 0x6a, 0x05, 0xde, 0x2f, 0x70, 0x95,
	0xb3, 0x14, 0x68, 0xaf, 0x7b, 0xf5, 0xf6, 0xe1, 0x67, 0x0b, 0x8c, 0x9c, 0x99, 0x44, 0xb8, 0x58,
	0x20, 0x33, 0x6f, 0x2d, 0x2a, 0x4b, 0x7f, 0x5f, 0x68, 0x7c, 0x3d, 0x51, 0xbe, 0x1e, 0xc2, 0x07,
	0x7d, 0x7c, 0xb5, 0x4c, 0x75, 0xf6, 0x64, 0x66, 0x3d, 0x4e, 0x5f, 0x0e, 0xed, 0x75, 0x2f, 0xde,
	0xfe, 0xf2, 0xd2, 0xe1, 0xb1, 0x63, 0x1d, 0x1d, 0x3b, 0xd6, 0xb7, 0x63, 0xc7, 0x3a, 0x38, 0x71,
	0x4a, 0x47, 0x27, 0x4e, 0xe9, 0xcb, 0x89, 0x53, 0x5a, 0x77, 0xba, 0x1b, 0xec, 0x74, 0xb7, 0x90,
	0xbb, 0x09, 0x15, 0x0d, 0x5b, 0x7d, 0xb6, 0x17, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xe1,
	0x4c, 0xb2, 0x92, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetLct Queries a list of GetLct items.
	GetLct(ctx context.Context, in *QueryGetLctRequest, opts ...grpc.CallOption) (*QueryGetLctResponse, error)
	// GetComponentRelationships Queries a list of GetComponentRelationships items.
	GetComponentRelationships(ctx context.Context, in *QueryGetComponentRelationshipsRequest, opts ...grpc.CallOption) (*QueryGetComponentRelationshipsResponse, error)
	// ValidateLctAccess Queries a list of ValidateLctAccess items.
	ValidateLctAccess(ctx context.Context, in *QueryValidateLctAccessRequest, opts ...grpc.CallOption) (*QueryValidateLctAccessResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/racecarweb.lctmanager.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLct(ctx context.Context, in *QueryGetLctRequest, opts ...grpc.CallOption) (*QueryGetLctResponse, error) {
	out := new(QueryGetLctResponse)
	err := c.cc.Invoke(ctx, "/racecarweb.lctmanager.v1.Query/GetLct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetComponentRelationships(ctx context.Context, in *QueryGetComponentRelationshipsRequest, opts ...grpc.CallOption) (*QueryGetComponentRelationshipsResponse, error) {
	out := new(QueryGetComponentRelationshipsResponse)
	err := c.cc.Invoke(ctx, "/racecarweb.lctmanager.v1.Query/GetComponentRelationships", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidateLctAccess(ctx context.Context, in *QueryValidateLctAccessRequest, opts ...grpc.CallOption) (*QueryValidateLctAccessResponse, error) {
	out := new(QueryValidateLctAccessResponse)
	err := c.cc.Invoke(ctx, "/racecarweb.lctmanager.v1.Query/ValidateLctAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetLct Queries a list of GetLct items.
	GetLct(context.Context, *QueryGetLctRequest) (*QueryGetLctResponse, error)
	// GetComponentRelationships Queries a list of GetComponentRelationships items.
	GetComponentRelationships(context.Context, *QueryGetComponentRelationshipsRequest) (*QueryGetComponentRelationshipsResponse, error)
	// ValidateLctAccess Queries a list of ValidateLctAccess items.
	ValidateLctAccess(context.Context, *QueryValidateLctAccessRequest) (*QueryValidateLctAccessResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetLct(ctx context.Context, req *QueryGetLctRequest) (*QueryGetLctResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLct not implemented")
}
func (*UnimplementedQueryServer) GetComponentRelationships(ctx context.Context, req *QueryGetComponentRelationshipsRequest) (*QueryGetComponentRelationshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentRelationships not implemented")
}
func (*UnimplementedQueryServer) ValidateLctAccess(ctx context.Context, req *QueryValidateLctAccessRequest) (*QueryValidateLctAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateLctAccess not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/racecarweb.lctmanager.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/racecarweb.lctmanager.v1.Query/GetLct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLct(ctx, req.(*QueryGetLctRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetComponentRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetComponentRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetComponentRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/racecarweb.lctmanager.v1.Query/GetComponentRelationships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetComponentRelationships(ctx, req.(*QueryGetComponentRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidateLctAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidateLctAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidateLctAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/racecarweb.lctmanager.v1.Query/ValidateLctAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidateLctAccess(ctx, req.(*QueryValidateLctAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "racecarweb.lctmanager.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetLct",
			Handler:    _Query_GetLct_Handler,
		},
		{
			MethodName: "GetComponentRelationships",
			Handler:    _Query_GetComponentRelationships_Handler,
		},
		{
			MethodName: "ValidateLctAccess",
			Handler:    _Query_ValidateLctAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "racecarweb/lctmanager/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLctRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLctRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLctRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LctId) > 0 {
		i -= len(m.LctId)
		copy(dAtA[i:], m.LctId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LctId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLctResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLctResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLctResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LinkedContextToken) > 0 {
		i -= len(m.LinkedContextToken)
		copy(dAtA[i:], m.LinkedContextToken)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LinkedContextToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetComponentRelationshipsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetComponentRelationshipsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetComponentRelationshipsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ComponentId) > 0 {
		i -= len(m.ComponentId)
		copy(dAtA[i:], m.ComponentId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ComponentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetComponentRelationshipsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetComponentRelationshipsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetComponentRelationshipsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LctCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LctCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ComponentRelationships) > 0 {
		i -= len(m.ComponentRelationships)
		copy(dAtA[i:], m.ComponentRelationships)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ComponentRelationships)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidateLctAccessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidateLctAccessRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidateLctAccessRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestorId) > 0 {
		i -= len(m.RequestorId)
		copy(dAtA[i:], m.RequestorId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RequestorId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.LctId) > 0 {
		i -= len(m.LctId)
		copy(dAtA[i:], m.LctId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LctId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidateLctAccessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidateLctAccessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidateLctAccessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccessLevel) > 0 {
		i -= len(m.AccessLevel)
		copy(dAtA[i:], m.AccessLevel)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccessLevel)))
		i--
		dAtA[i] = 0x12
	}
	if m.HasAccess {
		i--
		if m.HasAccess {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLctRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LctId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLctResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LinkedContextToken)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetComponentRelationshipsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ComponentId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetComponentRelationshipsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ComponentRelationships)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LctCount != 0 {
		n += 1 + sovQuery(uint64(m.LctCount))
	}
	return n
}

func (m *QueryValidateLctAccessRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LctId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RequestorId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidateLctAccessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HasAccess {
		n += 2
	}
	l = len(m.AccessLevel)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLctRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLctRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLctRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LctId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LctId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLctResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLctResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLctResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkedContextToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LinkedContextToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetComponentRelationshipsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetComponentRelationshipsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetComponentRelationshipsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComponentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ComponentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetComponentRelationshipsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetComponentRelationshipsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetComponentRelationshipsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComponentRelationships", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ComponentRelationships = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LctCount", wireType)
			}
			m.LctCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LctCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidateLctAccessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidateLctAccessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidateLctAccessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LctId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LctId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidateLctAccessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidateLctAccessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidateLctAccessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasAccess", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasAccess = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessLevel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessLevel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
