#!/bin/bash
# Setup for ACT Society Federation
# Two societies discovering and joining as peers

NODE_ID="c1a129e14fad4cb7c95f9e2b5e9586013941ebf5"
THIS_IP="10.0.0.72"

echo "=== ACT Federation Setup ==="
echo ""
echo "Society 1 Details:"
echo "Node ID: $NODE_ID"
echo "Network: $THIS_IP:26656"
echo "RPC: http://$THIS_IP:26657"
echo "API: http://$THIS_IP:1317"
echo ""
echo "For Society 2 on the other machine:"
echo ""
echo "1. Pull and build ACT:"
echo "   git clone https://github.com/dp-web4/ACT.git"
echo "   cd ACT/implementation/ledger"
echo "   ignite chain build --skip-proto"
echo ""
echo "2. Copy this genesis file to Society 2:"
echo "   scp genesis_for_federation.json user@OTHER_MACHINE:/path/to/act/genesis.json"
echo ""
echo "3. On Society 2, initialize with shared genesis:"
echo "   racecar-webd init society2 --chain-id act-web4 --home ./society2"
echo "   cp genesis.json ./society2/config/genesis.json"
echo ""
echo "4. Configure Society 2 to connect here:"
echo "   Edit society2/config/config.toml:"
echo "   persistent_peers = \"${NODE_ID}@${THIS_IP}:26656\""
echo ""
echo "5. Start Society 2 with different ports:"
echo "   racecar-webd start --home ./society2 \\"
echo "     --p2p.laddr tcp://0.0.0.0:26657 \\"
echo "     --rpc.laddr tcp://0.0.0.0:26658 \\"
echo "     --grpc.address 0.0.0.0:9091 \\"
echo "     --api.address tcp://0.0.0.0:1318"
echo ""
echo "Once connected, the societies will sync and can interact!"